# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.srcs/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0.xci
# IP: The module: 'artyz7_bd_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyz7_bd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyz7_bd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyz7_bd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.srcs/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0.xci
# IP: The module: 'artyz7_bd_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyz7_bd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyz7_bd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyz7_bd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
