# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/artyz7_bd/artyz7_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd || ORIG_REF_NAME==artyz7_bd} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_processing_system7_0_0/artyz7_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_processing_system7_0_0 || ORIG_REF_NAME==artyz7_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_clk_wiz_0_0/artyz7_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_clk_wiz_0_0 || ORIG_REF_NAME==artyz7_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axi_gpio_0_0/artyz7_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axi_gpio_0_0 || ORIG_REF_NAME==artyz7_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_xbar_0/artyz7_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_xbar_0 || ORIG_REF_NAME==artyz7_bd_xbar_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_ps7_0_axi_periph_0/artyz7_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==artyz7_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_rst_ps7_0_100M_0/artyz7_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==artyz7_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axi_quad_spi_0_0/artyz7_bd_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axi_quad_spi_0_0 || ORIG_REF_NAME==artyz7_bd_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axi_gpio_1_0/artyz7_bd_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axi_gpio_1_0 || ORIG_REF_NAME==artyz7_bd_axi_gpio_1_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axi_gpio_2_0/artyz7_bd_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axi_gpio_2_0 || ORIG_REF_NAME==artyz7_bd_axi_gpio_2_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_xlconcat_0_0/artyz7_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_xlconcat_0_0 || ORIG_REF_NAME==artyz7_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axi_dma_0_0/artyz7_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axi_dma_0_0 || ORIG_REF_NAME==artyz7_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_xbar_1/artyz7_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_xbar_1 || ORIG_REF_NAME==artyz7_bd_xbar_1} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axi_mem_intercon_0/artyz7_bd_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axi_mem_intercon_0 || ORIG_REF_NAME==artyz7_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_axis_data_fifo_0_0/artyz7_bd_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_axis_data_fifo_0_0 || ORIG_REF_NAME==artyz7_bd_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_auto_pc_0/artyz7_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_auto_pc_0 || ORIG_REF_NAME==artyz7_bd_auto_pc_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_auto_us_0/artyz7_bd_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_auto_us_0 || ORIG_REF_NAME==artyz7_bd_auto_us_0} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_auto_us_1/artyz7_bd_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_auto_us_1 || ORIG_REF_NAME==artyz7_bd_auto_us_1} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_auto_pc_1/artyz7_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_auto_pc_1 || ORIG_REF_NAME==artyz7_bd_auto_pc_1} -quiet] -quiet

# IP: bd/artyz7_bd/ip/artyz7_bd_system_ila_0_0/artyz7_bd_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyz7_bd_system_ila_0_0 || ORIG_REF_NAME==artyz7_bd_system_ila_0_0} -quiet] -quiet

# XDC: /home/parallels/artyz7_dsp_2020-2/artyz7_dsp_2020-2.gen/sources_1/bd/artyz7_bd/artyz7_bd_ooc.xdc
